### ISSUE TITLE
Port from Moose to Moo

### ISSUE THREAD

**Issue by tobyink** [pablrod/p5-Bat-Interpreter#10]
Would you accept a patch to port Bat::Interpreter and App::BatParser from Moose to Moo?

Moo is a lightweight replacement for Moose, and will automatically upgrade your roles and classes to full Moose roles and classes when it detects that Moose has been loaded. Switching from Moose to Moo should make the code faster, have fewer dependencies, and use less memory, but still allow people to use Moose to write extensions (new delegates, etc) if they like.

From a quick check of your code, it looks like it would be a pretty trivial change — a few lines of code per module, with no impact on the test suite.

**Comment by pablrod** [comment]
Yes!

We have some delegates running in production right now, so perhaps I need some time to check those delegates (or add more tests). But if it's as straightforward as you say it will be quick!

**Comment by tobyink** [comment]
Done pull requests for both projects.

**Comment by pablrod** [comment]
Yeaah!! Thank you!!

I need one or two days to make some checks, but at first glance everything looks good!

**Comment by pablrod** [comment]
Everything is working fine!!
