### ISSUE TITLE
Lowercase "neq" not being parsed.

### ISSUE THREAD

**Issue by sergiotarxz** [pablrod/p5-Bat-Interpreter#19]
Good morning, I've found something that I think is a bug.

## Description

The `NEQ` operator can only be used in uppercase and is refused to be executed in lowercase.

## Steps to reproduce

```batch
if "03" neq "05" echo "hello world"
```

This line works in Windows but is refused to be executed under p5-Bat-Interpreter.

## Example error.

```
Operator: neq not implemented at /opt/perlbrew/perls/perl-5.24.4/lib/site_perl/5.24.4/Bat/Interpreter.pm line 289.
```

Thanks for your time dear maintainers.

**Comment by pablrod** [comment]
I'll fix it ASAP
